unifi:
  host: ${oc.env:UNIFI_HOST}
  username: ${oc.env:UNIFI_USERNAME}
  password: ${oc.env:UNIFI_PASSWORD}
  port: ${oc.env:UNIFI_PORT,443}
  site: ${oc.env:UNIFI_SITE,default}
  verify_ssl: ${oc.env:UNIFI_VERIFY_SSL,true}

server:
  host: ${oc.env:SERVER_HOST,127.0.0.1}
  port: ${oc.env:SERVER_PORT,3000}
  log_level: ${oc.env:LOG_LEVEL,INFO}
  
permissions:

  default:
    create: true
    update: true

  firewall_policies:
    create: true
    update: true
    
  traffic_routes:
    create: true
    update: true
    
  port_forwards:
    create: true
    update: true
    
  qos_rules:
    create: true
    update: true
    
  vpn_clients:
    create: true
    update: true

  networks:
    create: true  # Provisioning a new network can disrupt traffic
    update: true  # Changing subnets, VLANs, DHCP ranges requires care

  wlans:
    create: true
    update: true

  devices:
    create: true  # Adoption / provisioning – normally handled by controller, not tools
    update: true  # Firmware upgrade, rename, etc.

  clients:
    create: true  # Not applicable, but kept for symmetry
    update: true  # Block/unblock, rename, reconnect

  vpn_servers:
    create: true
    update: true