name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-asyncio
    
    - name: Run tests
      run: |
        pytest tests/ || echo "No tests yet"
    
    - name: Check imports
      run: |
        python -c "from src.main import main; print('Import successful')"

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t unifi-network-mcp:test .
    
    - name: Test Docker image
      run: |
        docker run --rm unifi-network-mcp:test --help || true

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install linting tools
      run: |
        pip install ruff mypy
    
    - name: Run ruff
      run: |
        ruff check src/ || true
    
    - name: Run mypy
      run: |
        mypy src/ --ignore-missing-imports || true